### ISSUE TITLE
How to use and post calendars

### ISSUE THREAD

**Issue by Chilliwack** [FredHutch/coop#11]
**Blog post author:**_(anyone specific writing this?)_
@Chilliwack

**Blog post idea:**_(please include 1-2+ sentences on what the post will be about)_
Calendar events - How to use and post calendars

https://docs.google.com/document/d/19u00BdkrDbA2rKfx1F61jEeiNay7GF5-zDlfdYx5fsU/edit

**Comment by k8hertweck** [comment]
This seems less necessary now because we clarified the calendar page in the Coop blog: https://fredhutch.github.io/coop/calendar/
