### ISSUE TITLE
Remove errant files in assets

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/coop#115]
**Describe the bug**
There's some errant files (inferred from weird filenames) included in [assets](https://github.com/FredHutch/coop/tree/gh-pages/assets/slack-new) that need to be cleaned up. I think the entire directory called `![slack_convo](` can be deleted, but we should check this isn't actually being used for images for any posts.

**Comment by Chilliwack** [comment]
this is from the image plugin creating these directories and is being used to render the post. Ill look into deleting the `![slack_convo])` if its not needed but the overall structure is needed and there by default.
