### ISSUE TITLE
How to ask for help with coding problems

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/coop#130]
**Title:** _Asking for assistance with computing problems_

**Category:** _Community, Technical_

**Tags:** _office hours, community groups_

**Blog content:**

- https://stackoverflow.com/help/how-to-ask
- [Ten Simple Rules](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1002202)

**Comment by lakikowolfe** [comment]
Completed issue with PR 149
