### ISSUE TITLE
Post: how the Coop team is managing remote work (and how you can, too!)

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/coop#133]
As discussed with @strasser:

- daily standups: what we discuss
- willingness to jump on calls
- shifts in work priorities and expectations

**Comment by strasser** [comment]
https://docs.google.com/document/d/1K1iJr7Sk3T5IIgbo4cWBzZwnWcshVKOL-Pts0AXDaSQ/edit

**Comment by strasser** [comment]
ICYMI in slack threads, this is ready to be posted!

**Comment by Chilliwack** [comment]
Cool beans, Ill post in an hour

**Comment by Chilliwack** [comment]
posted https://fredhutch.github.io/coop/community/remote-teamwork/
