### ISSUE TITLE
blog on FARM in Markdown!

### ISSUE THREAD

**Issue by strasser** [FredHutch/coop#139]
**Title:** _(A short, catchy description to entice readers)_

**Category:** _(choose Community, Technical, or Science as described in the contributing guidelines)_

**Tags:** _(Suggested keywords that can help readers find information from among our blog posts)_

# Coop FARM: Facilitating and Advancing Research through Matchmaking

Priorities and tasks have changed substantially across the Hutch due to COVID-19 and social distancing. Some people have extra time to devote to computational projects. FARM is an effort to connect people with time and computational skills with projects that might need their help. It’s short for “facilitating and advancing research through matchmaking”. Please note this is a pilot; we anticipate that we will need to revisit forms, structures, and procedures often. 

**Have an idea for a project? Need some help with an existing project?** Fill out [this form](https://airtable.com/shr2J0biP5BJy6aIT).

**Interested in volunteering or mentoring?** Fill out [this form](https://airtable.com/shr2hdDia0VVFbcrn).

## How it will work

When projects come in, a Coop team member will be assigned to assess the project, determine the feasibility, and assess scope. The team member will connect with the proposer to get more information and manage expectations. Once the project is assessed, potential matches will be evaluated from the volunteers list. The team member will then meet with the proposer and the volunteer(s) to ensure clarity in the project, expectations, and deliverables.
 
## FAQ for Volunteers

**I have skills to share or would like to host an informal learning session. How do I do that?**
We are always looking for community members to share a skill or teach others something. Please fill out the [volunteer form](https://airtable.com/shr2hdDia0VVFbcrn) and add a note about your idea.

**I only have an hour or two a week available to volunteer. Is it worth it?**
Absolutely! We are hoping to get a lot of different types and sizes of projects, and your time is valuable no matter how big or small.

**Can I pick the project I work on?**
We will work behind the scenes to match projects and volunteers. We will contact you about potential good fits and give you an opportunity to “veto” if you are uninterested or unwilling.

**What if I don’t have super coding skills but want to help?**
Wiki stuff for those that have time and not necessarily lots of skills. Basic “how to contribute” guide Read [this guide](https://github.com/FredHutch/wiki/blob/master/README.md) on how to get started. You can also act as a reviewer for the wiki.
 
**I need some extra cash! Are there any options for that?**
Check out the [Wiki Writers Program](https://sciwiki.fredhutch.org/outreach/) - get paid for making the SciWiki a better resource for everyone.

**I’m more interested in taking an online course to up my skills. What do you suggest?**
We have resources for that too! 
- [Fredhutch.io](http://www.fredhutch.io/)  has classes in Intro to Python, Intro to R, and more. Register for real-time, instructor led courses through Hutch Learning (more sessions to be listed soon, you can select the option to be notified of new sessions).  
- [Course materials](http://www.fredhutch.io/resources/)  are also publicly available online for reading and working at your own pace. 
- For information about both data generation and scientific computing, check out the  [Fred Hutch Biomedical Data Science Wiki](https://sciwiki.fredhutch.org/). In particular, the page on  [Training, Community, and Finding Help](https://sciwiki.fredhutch.org/scicomputing/reference_training/)  describes opportunities for office hours and community discussion groups for different topics.

## FAQ for projects

**What kinds of projects are appropriate?**
Here are some examples: 
- improving data visualization for a set of data
- reformatting data to a necessary format for ingest into a platform like Oncoscape
- Application of machine learning to a data set.
- Adapting existing code to package format (e.g., accommodating standards for CRAN or PEP8)
- Developing pipelines or workflows
 
**I have a rough idea of a project but it’s not thought out completely. Is that okay?**
Yes! Fill out the form to get started and we will work with you to understand your needs and scope the project.  

**Can I pick the volunteers to work on my project?**
Although we will happily take suggestions of specific people, we will work behind the scenes to match projects and volunteers.
    
**Do I have to work on my project too or can it be 100% someone else?**
Although you might not be the primary workhorse for the project, we need you to be at least available to connect with the volunteer(s) and answer questions and provide guidance.

**Comment by k8hertweck** [comment]
Sadly, not within scope of current activities now or in the near future.
