### ISSUE TITLE
Copy edit descriptions and templates

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/coop#151]
- revise/clarify [About page](https://fredhutch.github.io/coop/about/)
- issue templates

**Comment by lakikowolfe** [comment]
Working on editing the about page

**Comment by k8hertweck** [comment]
@lakikowolfe Now that you've had a chance to get a feel for our publication process, could you take a look at revising the issue and pull request templates? They're both in the `.github` folder. I feel like they're too long, and perhaps redundant, and I'd like to see them streamlined.

**Comment by k8hertweck** [comment]
Resolved by #184
