### ISSUE TITLE
Set up Travis CI to check for broken links

### ISSUE THREAD

**Issue by lakikowolfe** [FredHutch/coop#179]
Recently Helen brought a dead link to my attention. I think it'd be good to check for these things regularly. Seems like using Travis CI might be the solution.

https://jekyllrb.com/docs/continuous-integration/travis-ci/

**Comment by lakikowolfe** [comment]
- https://docs.travis-ci.com/user/deployment/pages/

**Comment by lakikowolfe** [comment]
Travis is no longer free to use

**Comment by k8hertweck** [comment]
Yes it is! https://docs.travis-ci.com/user/travis-ci-for-private/#why-cant-i-find-information-on-pricing-on-travis-ciorg
