### ISSUE TITLE
Quarterly goals

### ISSUE THREAD

**Issue by lakikowolfe** [FredHutch/coop#192]
**Description:** _(Describe your idea!)_
Kate to write a post on our upcoming quarterly goals

**Related values:** _(You can reference the Coop Values [here](https://fredhutch.github.io/coop/community/coop-values/))_
community-centered, open

**Reference:** _(What articles/papers/conversations inspired this post and/or will be used for reference?)_

**Category:** _(choose Community, Technical, or Science as described in the contributing guidelines)_
Community

**Tags:** _(Suggested keywords that can help readers find information from among our blog posts)_
_Please first reference [this list](https://fredhutch.github.io/coop/about/) of pre-existing tags_
Announcement
Strategy

**Comment by k8hertweck** [comment]
resolved by #201
