### ISSUE TITLE
dead link in about page

### ISSUE THREAD

**Issue by lakikowolfe** [FredHutch/coop#195]
**Describe the bug**
Dead link on about page. I removed it with a comment but the link is `https://research.fhcrc.org/coop/en/community/participate.html`

What was this pointing to? Do we need to replace it?

**To Reproduce**
1. Navigate to about page
2. click the link (https://research.fhcrc.org/coop/en/community/participate.html)

**Expected behavior**
render page

**Screenshots**
NA

**Desktop (please fill out as much as you are able):**
On MacBook pro using chrome

**Smartphone (please fill out as much as you are able):**
NA

**Additional context**
NA

**Comment by k8hertweck** [comment]
The "participate" page used to be nested under community, so it can be replaced with that one (the pages have been consolidated): https://research.fhcrc.org/coop/en/community.html
