### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/coop#2]
- Create `CONTRIBUTING.md` 
- Create template for blog posts

**Comment by Chilliwack** [comment]
OK so the blog is rendering from coop/master as the default...I didnt create a gh-pages branch bc it seems based on our setup that we have a higher level org on github ie FredHutch which has this blog and everything else FH makes in the orgs master repo already so breaking this repo which is just a gh page into two branches where one serves the gh pages just seems redundant so for now Ill keep it how it is but can easily break this out into its own gh-pages branch.

**Comment by Chilliwack** [comment]
soooooo...I ended up creating a gh-pages branch just to play nicely with the github git-pages gem plugin for jekyll. So..now the "data" for this blog if we had any lives in master but the whole plog html etc renders from gh-pages. We do not have to do this..for simplicity we could render from master or master/docs..both are options if we want a cleaner repo with one branch

**Comment by k8hertweck** [comment]
Picking up style issues in #72
