### ISSUE TITLE
Plan for blog categories/tags

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/coop#34]
Minimal mistakes includes an option to define categories, which are like tags, but then rendered together in [Posts by category](https://fredhutch.github.io/coop/categories/) on the website. We should plan ahead for what types of categories we want, which include appealing to a very broad audience. I propose something like the following:

- community: notes about Coop community events, including announcements
- technical: posts that describe specific tools, approaches, or solutions from folks in our community. This would also be the place that some posts from our coding groups could go. 
- science: descriptions of research from folks in our community. 
- Others?

We could even match these with labels in issues, to make sure we've got a strategy in place for communicating to different parts of our community.

**Comment by k8hertweck** [comment]
Closing this because I'm fairly set on the three main categories, we'll use #41 to address the scope and logistics of tags

**Comment by Chilliwack** [comment]
Kewl.....to kinda standardize things and since you've settled on the 3 cats meow...I've gone ahead and just added the other 2 but commented them out in the post. I do this for the temps as well so we always have the categories there and we just comment in/out the right ones..
