### ISSUE TITLE
Coop team introductions

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/coop#37]
- [ ] Kate
- [ ] Lauren
- [ ] Anders
- [ ] Brenda
- [ ] Gabi

**Blog post idea:**
Describe rolls and responsibilities for existing team members

**Comment by Chilliwack** [comment]
@k8hertweck I went ahead and made a branch https://github.com/FredHutch/coop/tree/coop-team-intro and committed https://github.com/FredHutch/coop/commit/cf16211446d2981cd75a6ad139c755f2003c3910 the blog outline or base plate and added my stuff. Didnt do a PR bc I figure everyone else would like to commit to this branch with there additions before PRing. Let me know if you want me to ghost write for the others. If not I'll move on to another blog post...

**Comment by k8hertweck** [comment]
Let's talk in March to solidify who we should include in this list, and what information would be most useful to report.

**Comment by lakikowolfe** [comment]
@k8hertweck should this info be incorporated into the about.md? I was thinking about this re: Issue #151

**Comment by lakikowolfe** [comment]
lol wait nevermind I see that you mentioned linking this in the about page above. Still interested in your more current thoughts.

**Comment by k8hertweck** [comment]
Let's close this issue and delete the draft file associated with this; I'm adding info about instructors to fredhutch.io so that can help highlight people involved for now.
