### ISSUE TITLE
Add author attribution

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/coop#39]
Each post needs to be able to have an author listed. it would also be great to have a page that lists all authors (with links out to their preferred contact info, like twitter, GitHub, webpage etc)

**Comment by k8hertweck** [comment]
We talked about making many community announcements with the author of "The Coop" or "The Coop Team", which would be modified from the current long name for the org.

Anytime there's personal exposition or opinion, we'll include an individual's name (e.g., Kate or Justin) as author.

**Comment by k8hertweck** [comment]
Also see #64

**Comment by k8hertweck** [comment]
Need to update CONTRIBUTING.md as well

**Comment by Chilliwack** [comment]
Closing this out since the fix is live but I'm going to keep this issue in the project until I have a chance to review with ya that youre happy with everything here..
