### ISSUE TITLE
Add tags back

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/coop#41]
Need to be updated:
- [x] _data/navigation.yml
- [x] hello world blog post

Also involves FredHutch/coop_temp#34

**Comment by k8hertweck** [comment]
So my thinking is that we'll have categories be capitalized and very limited (Community, Technical, Science) and tags can be lowercase and much more diverse. Here are some ideas for tags (not inclusive, only examples):

Community groups:
- r
- python
- data_viz
- shiny
- nextflow

Other languages, approaches, or Slack channels:
- unix
- javascript
- labkey
- tableau
- cloud

One for division or part of Fred Hutch:
- PHS
- HDC
- STTR

**Comment by Chilliwack** [comment]
@Chilliwack add applicable tags to hello world and make sure they are rendering properly...

**Comment by k8hertweck** [comment]
Each post gets a category of Science, Technical, Community.

Guidelines for tags:
- two to four tags per post
- submitters recommend tags, reviewers make final selection

Consider developing tagging strategy based on category of post

**Comment by k8hertweck** [comment]
I've added sufficient information to the contributing guidelines

**Comment by k8hertweck** [comment]
Tags added to all published posts, and page featuring tags has been added
