### ISSUE TITLE
Add Google Analytics 

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/coop#60]
- [x] set up via coop gmail
- [x] add to `_config.yml`

**Comment by k8hertweck** [comment]
https://mmistakes.github.io/minimal-mistakes/docs/configuration/#analytics

**Comment by Chilliwack** [comment]
used fredhutchcoop and made changes to both prod and my local so I can test with prod and got data coming back as you can see..
![Screen Shot 2019-11-25 at 9 37 27 AM](https://user-images.githubusercontent.com/46973804/69564221-76f46e00-0f67-11ea-8d02-db965666d9cf.png)
