### ISSUE TITLE
Redo the authorship for the Coop identity

### ISSUE THREAD

**Issue by Chilliwack** [FredHutch/coop#64]
Carly[via email 11/26 @ 9:22 'Blog question'] - "can we just make this "The Coop"? Seems redundant since the masthead will always be above it...

![image](https://user-images.githubusercontent.com/46973804/69661627-95299f00-1037-11ea-88f1-aa76c9edf1dc.png)

**Comment by k8hertweck** [comment]
I'd mentioned this in a comment on the issue above.
