### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/coop#74]
Creating a PR template may help scale up our ability to accept community submissions (and ease the process of getting newer folks onto GitHub). We can address this next spring, perhaps.

**Comment by Chilliwack** [comment]
** create a PULL_REQUEST_TEMPLATE.md for the  blog **
	- add check boxes
	- tests?
	- CI?
	- required tags and categories
	- title 
	- author?
	- etc?

**Comment by Chilliwack** [comment]
did this https://github.com/FredHutch/coop/pull/90 on Friday but the PR temp is not showing up when I try to create PRs off of gh-pages. Going to investigate further to have this show up as a.

**Comment by Chilliwack** [comment]
I got this working and its done. You can see it here https://github.com/FredHutch/coop/blob/gh-pages/.github/pull_request_template.md or when you do a PR.
