### ISSUE TITLE
How to use Slack

### ISSUE THREAD

**Issue by Chilliwack** [FredHutch/coop#9]
**Blog post author:**_(anyone specific writing this?)_
@Chilliwack 

**Blog post idea:**_(please include 1-2+ sentences on what the post will be about)_
https://docs.google.com/document/d/1o1Rhm9hqip8vCwCUK7uuOyKUGF5v6LQWl7rW21REEhA/edit

**Comment by k8hertweck** [comment]
I've split the slack content into three separate posts (all in `drafts`), with the idea being:

1. `slack-new.md` overviews what slack is and why people should join it, but kind of assumes people will be lurking for awhile
2. `slack-discussions.md` includes things like etiquette for using slack and all that fun stuff, and tries to get people to think about how to engage more
3. `slack-personalizing.md` is about how to manage communication overload

**Comment by Chilliwack** [comment]
In an effort to get the ~~three~~ two posts about slack ready to publish whenever you are ready I went ahead and tightened them up..

- `slack-new.md` added tags; added author 'The Coop Team'; word-smith the channels; added image; and linked to `slack-discussions.md` 
- `slack-discussions.md` added tags; added author; retitled the post; also did some word-smithing and added links out to `slack-new.md`
- 'slack-personalizing.md' added the profile and gif parts to `slack-discussions.md` and deleted `slack-personalizing.md` since there wasnt much content left to make it a blog post

Committed my changes and submitted a draft PR https://github.com/FredHutch/coop/pull/94 . Let me know if you want me to make any changes else feel free to publish whenever..

**Comment by Chilliwack** [comment]
- Publish slack post #1 https://github.com/FredHutch/coop/commit/3577c482329ba21b40e3c1f29f9382f3034783fd

- Publish slack post #2 https://github.com/FredHutch/coop/commit/8916a758e3a4362a372bc5882464843afdbce6e0
