### ISSUE TITLE
Do a write up on URSSI

### ISSUE THREAD

**Issue by Chilliwack** [FredHutch/coop#92]
**Title:** _(A short, catchy description to entice readers)_

Do a write up on URSSI

**Category:** _(choose Community, Technical, or Science as described in the contributing guidelines)_

**Tags:** _(Suggested keywords that can help readers find information from among our blog posts)_

**Blog content:** _(This is the body of the blog post! We recommend relatively short posts, no more than five paragraphs, equivalent to a three minute read. Pictures and links to other sites are also great!)_

**Comment by Chilliwack** [comment]
Hey @k8hertweck I wanted to quickly get some content posted about URSSI so I did this https://github.com/FredHutch/coop/pull/96 Let me know if you are cool with it and Ill publish.

**Comment by k8hertweck** [comment]
Schedule to publish Monday, Jan 13

**Comment by Chilliwack** [comment]
published https://fredhutch.github.io/coop/technical/URSSI/
